--- 
abstract: "a module to apply outstanding database deltas (files "
author: Gavin Carr <gavin@openfusion.com.au>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Delta
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBI: 0
version: 0.6
