---
abstract: 'a module to apply outstanding database deltas (files '
author:
  - 'Gavin Carr <gavin@openfusion.com.au>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Path: 2.08
  Test::Deep: 0
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Delta
no_index:
  directory:
    - inc
    - t
requires:
  DBI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.9.1
